### ISSUE TITLE
Congratulations and question

### ISSUE THREAD

**Issue by frederikhors** [biblius/hextacy#10]
First of all: congratulations!

I really like your readme content. I can feel your passion trying to fix a very complex problem: DB transaction within an hexagonal architecture written in Rust.

Really, thank you.

But even if I like you Readme I cannot understand your code.

Can I ask you something simpler?

In this project: https://github.com/skerkour/bloom-legacy the author is using DB in the service layer (you can read about the project here: https://kerkour.com/rust-web-application-clean-architecture).

My question to the author is about how to switch at runtime the DB implementation details: https://github.com/skerkour/bloom-legacy/issues/70.

Is `hextacy` capable of fixing this issue?

Can I start the project using Postgres or Mongo just writing the appropriate repository layer code and with a envinronment variable?

**Comment by biblius** [comment]
Hey there! I'm sorry for the late response, had some work stuff to do and totally missed the mail.

I'm really glad you like what I've done, it means a lot! :)

At the moment, I would not recommend you use hextacy for anything. It's a work in progress and I'm still figuring out the best way to expose the API to make it simple for everyone to use, but it's getting there!
I am currently rehauling the way its macros work internally and trying to integrate SeaORM into the whole thing. I'm planning on doing a video series detailing what exactly the crate does and how the internals of it work, so if you're interested in that you can star the project on github to get the latest updates.

As for your question, changing the drivers in runtime is not something I've thought about. Do you have a specific use case in mind to do so? I would be glad to introduce it to hextacy if it provides value.

I've never thought about changing drivers with an env variable, but I really like the idea! I'll see what I can do about it, but if you want to contribute and have in mind a way to implement it here, feel free to submit a PR :)

Currently I'm focusing on setting up SeaORM and macros, I know it can be kind of hard to read with all the layers of abstraction, but hopefully the video series will elaborate on why exactly it's necessary. But in essence, traits allow us to keep everything generic while macros are there just to reduce the boilerplate. If you have any specific questions about the project, feel free to ask!

Thanks for reaching out :D
